### ISSUE TITLE
MQTT client on same esp32    (connect via loop device)

### ISSUE THREAD

**Issue by derflaryam** [alexCajas/EmbeddedMqttBroker#12]
Is it possible to have a some mqtt client tasks running on the same ESP32 ?

**Comment by alexCajas** [comment]
Hi!, this library doesn't implement a functional mqtt client (It will be able in future versions), only use an abstracction to keep in the broker information of a real mqtt client. I usually use https://github.com/knolleary/pubsubclient, to use a broker and a client in the same sketch.
