### ISSUE TITLE
Use Broker & Client

### ISSUE THREAD

**Issue by Sungapelke** [alexCajas/EmbeddedMqttBroker#7]
Hello,

if I understand correctly, there is a client included in EmbeddedMqttBroker. How can I use this client in parallel with the broker. Publish and receive?
Thanks in advance

**Comment by alexCajas** [comment]
Hi!, thanks for intersting in this project!, for now, this library only implements a mqtt broker, MqttBroker::MqttClient class has basic information about the current state of connection with the external client and some logic to process its mqtt messages. In future versions, I will include a functional MqttClient but for now it is not developed. To do what you ask, I normaly use PubSubClient.h. There is no issue if you use both libraries in the same scketch. I hope it has helped you!
